### ISSUE TITLE
Slick Carousel broken in latest SF Spring 19 release.

### ISSUE THREAD

**Issue by TomSesselmann** [forcedotcom/aura#179]
There seems to be a bug with the `SecureDOMEvent.filterTouchesDescriptor` function in Aura Locker Service.

See the quick example I built which demonstrates the issue here https://dev4-vicpol-dev4.cs116.force.com/s/

The error occurs here https://github.com/forcedotcom/aura/blob/master/aura-resources/src/main/resources/aura/resources/lockerservice/aura-locker.js#L5617

And replacing `defineProperty` with `Object.defineProperty` fixes the error but I'm not sure if this is the best solution.

But basically, the defineProperty function is retuning the value "true" and not the object itself, and then the reduce function is calling defineProperty on "true" and not the new object, hence the error `defineProperty called on a non-object`

It was working fine before upgrading to Spring 19.

Any thoughts @jfparadis, @diervo ?

**Comment by TomSesselmann** [comment]
After a bit more digging I found that you're using `Reflect.defineProperty()` not `Object.defineProperty()`

```
Reflect.defineProperty()
Similar to Object.defineProperty(). Returns a Boolean.
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/defineProperty

Now I'm almost certain we need to be using `Object.defineProperty()` in this instance.

**Comment by TomSesselmann** [comment]
Thanks @jfparadis 👍 

Assuming the problem can be fixed easily, in your experience, how quickly can we expect it to be deployed to Salesforce? This bug is affecting a major release with a big APAC customer.

**Comment by jfparadis** [comment]
Fixed is complete. You should get it by Tuesday night. Reach us through org62 if want to discuss further.

**Comment by Rootcaller** [comment]
When this issue will be fixed?
I guess the latest commit didn't fix this bug.
